# Build arguments
ARG SOURCE_CODE=.
ARG VERSION
# Test Comment from RHOAI-2.23 6
# Base builder
FROM registry.redhat.io/ubi9-minimal@sha256:7c5495d5fad59aaee12abc3cbbd2b283818ee1e814b00dbc7f25bf2d14fa4f0c AS stage

RUN ls -la ./cachi2/output
RUN ls -la ./cachi2/output/deps

# Install packages for the install script and extract archives
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y unzip jq wget

RUN cd ./cachi2/output/deps/generic && \
    for file in *.zip; do unzip -d /root/ "$file"; done

###############################################################################
# Runtime image
FROM registry.redhat.io/ubi9/openjdk-21-runtime@sha256:26acabfda6160ef348ceebba38e6616c43bf98a18800bf6afc20913556389c06 as runtime


## Build args to be used at this step
ARG VERSION
ARG USERID=2000

LABEL com.redhat.component="odh-modelmesh-container" \
      name="managed-open-data-hub/odh-modelmesh-rhel8" \
      description="Modelmesh is a distributed LRU cache for serving runtime models" \
      summary="odh-modelmesh" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-modelmesh" \
      io.k8s.description="odh-modelmesh" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

USER root

RUN sed -i 's:security.provider.12=SunPKCS11:#security.provider.12=SunPKCS11:g' /usr/lib/jvm/java-21-openjdk-*/conf/security/java.security \
    && sed -i 's:#security.provider.1=SunPKCS11 ${java.home}/lib/security/nss.cfg:security.provider.12=SunPKCS11 ${java.home}/lib/security/nss.cfg:g' /usr/lib/jvm/java-21-openjdk-*/conf/security/java.security

COPY --from=stage root/target/dockerhome/ /opt/kserve/mmesh/
COPY --from=stage root/target/dockerhome/version /etc/modelmesh-version

# Make this the current directory when starting the container
WORKDIR /opt/kserve/mmesh

RUN echo "${VERSION}"

RUN useradd -c "Application User" -U -u ${USERID} -m app && \
    chown -R app:0 /home/app && \
    ln -s /opt/kserve/mmesh /opt/kserve/tas && \
    mkdir -p log && \
    chown -R app:0 . && \
    chmod -R 771 . && chmod 775 *.sh *.py && \
    echo "${VERSION}" > /opt/kserve/mmesh/build-version

EXPOSE 8080

# Run as non-root user by default, to allow runAsNonRoot:true without runAsUser
USER ${USERID}


# The command to run by default when the container is first launched
CMD ["sh", "-c", "exec /opt/kserve/mmesh/start.sh"]
