name: Trigger PNC Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'rhoai-*'
#    paths:
#      - build/operator-nudging.yaml

env:
  GITHUB_ORG: rhoai-rhtap
  SSO_SERVICE_ACCOUNT_NAME: ${{ secrets.SSO_SERVICE_ACCOUNT_NAME }}
  SSO_SERVICE_ACCOUNT_CLIENT_SECRET: ${{ secrets.SSO_SERVICE_ACCOUNT_CLIENT_SECRET }}
  PNC_PROFILE: ${{ secrets.PNC_PROFILE }}

permissions:
  contents: write

jobs:
  operator-processor:
    runs-on:
      - self-hosted
      - pnc
    container:
      image: quay.io/redhat-user-workloads/konflux-jbs-pnc-tenant/pnc/pnc-cli:48a761b5093bc474850b2ebcf06641825940deb7
      options: --user root
    steps:
      - name: List all files
        run: |
          pwd
          work_dir=pnc-$(date +%s)
          mkdir $work_dir
          cd $work_dir
          
          #install dependencies
          os="$(uname -s | tr '[:upper:]' '[:lower:]')"
          arch="$(uname -m | sed 's/x86_64/amd64/')"
          yq_version="v4.44.3"
          yq_filename="yq-$yq_version"
          echo "-> Downloading yq" >&2
          curl -sSfLo "$yq_filename" "https://github.com/mikefarah/yq/releases/download/$yq_version/yq_${os}_${arch}"
          chmod +x $yq_filename
          ln -s $yq_filename yq
          cp $yq_filename /usr/local/bin/yq
          
          BUILD_CONFIG_URL=rhoai-rhtap/RHOAI-Build-Config
          BUILD_CONFIG_REVISION=rhoai-2.13
          BUILD_CONFIG_PATH=odh-pig-builds/build-config.yaml
          
          echo -e "===================="
          
          echo -e "\nDownloading the build config ..."
          curl https://raw.githubusercontent.com/${BUILD_CONFIG_URL}/refs/heads/${BUILD_CONFIG_REVISION}/${BUILD_CONFIG_PATH} -o build-config.yaml
          
          echo -e "\nDownloading the PNC cli config ..."
          curl -k "https://gitlab.cee.redhat.com/project-ncl/utils/-/raw/master/konflux/configs/pnc_cli/config.yaml?ref_type=heads&inline=false" -o pnc-cli-config.yaml

          echo -e "\nReplacing credentials in the CLI config ..."
          envsubst '${SSO_SERVICE_ACCOUNT_NAME} ${SSO_SERVICE_ACCOUNT_CLIENT_SECRET}' < pnc-cli-config.yaml > config.yaml

          echo -e "\nStarting the PNC build ..."
          PNC_CLI_OUTPUT_FILE="pnc-cli-run-output.json"
          java -jar /home/jboss/bacon.jar pig run --mode=FORCE --downloadAttempts=3 . -p . --profile ${PNC_PROFILE} --jsonOutput > $PNC_CLI_OUTPUT_FILE
  
          echo -e "\nFinished the PNC build!"
          echo -e "\n=== PNC build output ==="
          cat $PNC_CLI_OUTPUT_FILE
          echo -e "===================="
  
          echo -e "\nGetting the list of built files (to be used later in the container build) ..."
          jq '[.builds[].builtArtifacts[]?.downloadUrl ]' "$PNC_CLI_OUTPUT_FILE" > "pnc-file-list.json"
          cat pnc-file-list.json
          
          jq '{metadata: {version: "1.0"}, artifacts: [.builds[].builtArtifacts[]? | select(.downloadUrl | endswith(".zip")) | {download_url: .downloadUrl , checksums: {sha256: .sha256}}] }' $PNC_CLI_OUTPUT_FILE | yq -p json > "generic_lockfile.yaml"
          cat generic_lockfile.yaml
          
          ls -l
          ls -l /home/jboss/
          cd ../
          rm -rf $work_dir